//! Generated serde models of the opencode OpenAPI 3.1 wire contract.
//!
//! AUTO-GENERATED by `scripts/codegen_opencode.py` from
//! `tests/schemas/opencode_openapi.json` (opencode 1.18.5). Do not edit by hand.

pub mod samples;
pub mod types;
