// AUTO-GENERATED by scripts/codegen_opencode.py — DO NOT EDIT BY HAND.

use serde_json::{json, Value};

/// Minimal valid JSON samples for the primary hand-wrapped endpoint types,
/// keyed by generated Rust type name. For round-trip tests.
pub fn endpoint_samples() -> Vec<(&'static str, Value)> {
    vec![
        ("SessionCreateParams", json!({})),
        ("PromptAsyncParams", json!({"parts": []})),
        ("SessionForkParams", json!({})),
        ("PermissionReplyParams", json!({"response": "once"})),
        ("PermissionReplyRequest", json!({"reply": "once"})),
        ("PermissionV2ReplyParams", json!({"reply": "once"})),
        ("QuestionReplyParams", json!({"answers": []})),
        (
            "Session",
            json!({"id": "x", "slug": "x", "projectID": "x", "directory": "x", "title": "x", "version": "x", "time": {"created": 0, "updated": 0}}),
        ),
        (
            "MessageWithParts",
            json!({"info": {"id": "x", "sessionID": "x", "role": "user", "time": {"created": 0.0}, "agent": "x", "model": {"providerID": "x", "modelID": "x"}}, "parts": []}),
        ),
        (
            "Event",
            json!({"id": "x", "type": "models-dev.refreshed", "properties": {}}),
        ),
    ]
}
